export interface StockMetadata {
  symbol: string;
  name: string;
  sector: string;
  market: 'US' | 'TH';
}

export const STOCK_LIST: StockMetadata[] = [
  // THAI STOCKS
  { symbol: 'PTT.BK', name: 'PTT Public Company Limited', sector: 'Energy', market: 'TH' },
  { symbol: 'CPALL.BK', name: 'CP ALL Public Company Limited', sector: 'Consumer Staples', market: 'TH' },
  { symbol: 'AOT.BK', name: 'Airports of Thailand Public Company Limited', sector: 'Industrials', market: 'TH' },
  { symbol: 'SCB.BK', name: 'SCB X Public Company Limited', sector: 'Financials', market: 'TH' },
  { symbol: 'KBANK.BK', name: 'Kasikornbank Public Company Limited', sector: 'Financials', market: 'TH' },
  { symbol: 'ADVANC.BK', name: 'Advanced Info Service Public Company Limited', sector: 'Communication Services', market: 'TH' },
  { symbol: 'GULF.BK', name: 'Gulf Energy Development Public Company Limited', sector: 'Utilities', market: 'TH' },
  { symbol: 'BDMS.BK', name: 'Bangkok Dusit Medical Services Public Company Limited', sector: 'Health Care', market: 'TH' },
  { symbol: 'DELTA.BK', name: 'Delta Electronics (Thailand) Public Company Limited', sector: 'Technology', market: 'TH' },
  { symbol: 'PTTEP.BK', name: 'PTT Exploration and Production Public Company Limited', sector: 'Energy', market: 'TH' },
  { symbol: 'SCC.BK', name: 'The Siam Cement Public Company Limited', sector: 'Materials', market: 'TH' },
  { symbol: 'BBL.BK', name: 'Bangkok Bank Public Company Limited', sector: 'Financials', market: 'TH' },
  { symbol: 'KTB.BK', name: 'Krung Thai Bank Public Company Limited', sector: 'Financials', market: 'TH' },
  { symbol: 'CPN.BK', name: 'Central Pattana Public Company Limited', sector: 'Real Estate', market: 'TH' },
  { symbol: 'INTUCH.BK', name: 'Intouch Holdings Public Company Limited', sector: 'Communication Services', market: 'TH' },
  { symbol: 'TRUE.BK', name: 'True Corporation Public Company Limited', sector: 'Communication Services', market: 'TH' },
  { symbol: 'OR.BK', name: 'PTT Oil and Retail Business Public Company Limited', sector: 'Energy', market: 'TH' },
  { symbol: 'HMPRO.BK', name: 'Home Product Center Public Company Limited', sector: 'Consumer Discretionary', market: 'TH' },
  { symbol: 'EA.BK', name: 'Energy Absolute Public Company Limited', sector: 'Utilities', market: 'TH' },
  { symbol: 'MINT.BK', name: 'Minor International Public Company Limited', sector: 'Consumer Discretionary', market: 'TH' },
  { symbol: 'TOP.BK', name: 'Thai Oil Public Company Limited', sector: 'Energy', market: 'TH' },
  { symbol: 'BANPU.BK', name: 'Banpu Public Company Limited', sector: 'Energy', market: 'TH' },
  { symbol: 'IVL.BK', name: 'Indorama Ventures Public Company Limited', sector: 'Materials', market: 'TH' },
  { symbol: 'GPSC.BK', name: 'Global Power Synergy Public Company Limited', sector: 'Utilities', market: 'TH' },
  { symbol: 'TMB.BK', name: 'TMBThanachart Bank Public Company Limited', sector: 'Financials', market: 'TH' },
  { symbol: 'BCH.BK', name: 'Bangkok Chain Hospital Public Company Limited', sector: 'Health Care', market: 'TH' },
  { symbol: 'CBG.BK', name: 'Carabao Group Public Company Limited', sector: 'Consumer Staples', market: 'TH' },
  { symbol: 'KTC.BK', name: 'Krungthai Card Public Company Limited', sector: 'Financials', market: 'TH' },
  { symbol: 'BTS.BK', name: 'BTS Group Holdings Public Company Limited', sector: 'Industrials', market: 'TH' },
  { symbol: 'BEM.BK', name: 'Bangkok Expressway and Metro Public Company Limited', sector: 'Industrials', market: 'TH' },

  // US STOCKS
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Technology', market: 'US' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'TSLA', name: 'Tesla, Inc.', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Technology', market: 'US' },
  { symbol: 'META', name: 'Meta Platforms, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Inc.', sector: 'Financials', market: 'US' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financials', market: 'US' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health Care', market: 'US' },
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financials', market: 'US' },
  { symbol: 'MA', name: 'Mastercard Incorporated', sector: 'Financials', market: 'US' },
  { symbol: 'PG', name: 'Procter & Gamble Company', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated', sector: 'Health Care', market: 'US' },
  { symbol: 'HD', name: 'The Home Depot, Inc.', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'BAC', name: 'Bank of America Corporation', sector: 'Financials', market: 'US' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Health Care', market: 'US' },
  { symbol: 'DIS', name: 'The Walt Disney Company', sector: 'Communication Services', market: 'US' },
  { symbol: 'NFLX', name: 'Netflix, Inc.', sector: 'Communication Services', market: 'US' },
  { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'CRM', name: 'Salesforce, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'CSCO', name: 'Cisco Systems, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Technology', market: 'US' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'PYPL', name: 'PayPal Holdings, Inc.', sector: 'Financials', market: 'US' },
  { symbol: 'NKE', name: 'NIKE, Inc.', sector: 'Consumer Discretionary', market: 'US' },
];
