export interface StockMetadata {
  symbol: string;
  name: string;
  sector: string;
  market: 'US' | 'TH';
}

// THAI STOCKS (SET50/SET100 focus)
export const TH_STOCKS: StockMetadata[] = [
  { symbol: 'PTT.BK', name: 'PTT Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'CPALL.BK', name: 'CP ALL Public Company Limited', sector: 'Commerce', market: 'TH' },
  { symbol: 'AOT.BK', name: 'Airports of Thailand Public Company Limited', sector: 'Transportation & Logistics', market: 'TH' },
  { symbol: 'SCB.BK', name: 'SCB X Public Company Limited', sector: 'Banking', market: 'TH' },
  { symbol: 'KBANK.BK', name: 'Kasikornbank Public Company Limited', sector: 'Banking', market: 'TH' },
  { symbol: 'ADVANC.BK', name: 'Advanced Info Service Public Company Limited', sector: 'Information & Communication Technology', market: 'TH' },
  { symbol: 'GULF.BK', name: 'Gulf Energy Development Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'BDMS.BK', name: 'Bangkok Dusit Medical Services Public Company Limited', sector: 'Health Care Services', market: 'TH' },
  { symbol: 'DELTA.BK', name: 'Delta Electronics (Thailand) Public Company Limited', sector: 'Electronic Components', market: 'TH' },
  { symbol: 'PTTEP.BK', name: 'PTT Exploration and Production Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'SCC.BK', name: 'The Siam Cement Public Company Limited', sector: 'Construction Materials', market: 'TH' },
  { symbol: 'BBL.BK', name: 'Bangkok Bank Public Company Limited', sector: 'Banking', market: 'TH' },
  { symbol: 'KTB.BK', name: 'Krung Thai Bank Public Company Limited', sector: 'Banking', market: 'TH' },
  { symbol: 'CPN.BK', name: 'Central Pattana Public Company Limited', sector: 'Property Development', market: 'TH' },
  { symbol: 'INTUCH.BK', name: 'Intouch Holdings Public Company Limited', sector: 'Information & Communication Technology', market: 'TH' },
  { symbol: 'TRUE.BK', name: 'True Corporation Public Company Limited', sector: 'Information & Communication Technology', market: 'TH' },
  { symbol: 'OR.BK', name: 'PTT Oil and Retail Business Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'HMPRO.BK', name: 'Home Product Center Public Company Limited', sector: 'Commerce', market: 'TH' },
  { symbol: 'EA.BK', name: 'Energy Absolute Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'MINT.BK', name: 'Minor International Public Company Limited', sector: 'Food & Beverage', market: 'TH' },
  { symbol: 'TOP.BK', name: 'Thai Oil Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'BANPU.BK', name: 'Banpu Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'IVL.BK', name: 'Indorama Ventures Public Company Limited', sector: 'Petrochemicals & Chemicals', market: 'TH' },
  { symbol: 'GPSC.BK', name: 'Global Power Synergy Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'TTB.BK', name: 'TMBThanachart Bank Public Company Limited', sector: 'Banking', market: 'TH' },
  { symbol: 'BCH.BK', name: 'Bangkok Chain Hospital Public Company Limited', sector: 'Health Care Services', market: 'TH' },
  { symbol: 'CBG.BK', name: 'Carabao Group Public Company Limited', sector: 'Food & Beverage', market: 'TH' },
  { symbol: 'KTC.BK', name: 'Krungthai Card Public Company Limited', sector: 'Finance & Securities', market: 'TH' },
  { symbol: 'BTS.BK', name: 'BTS Group Holdings Public Company Limited', sector: 'Transportation & Logistics', market: 'TH' },
  { symbol: 'BEM.BK', name: 'Bangkok Expressway and Metro Public Company Limited', sector: 'Transportation & Logistics', market: 'TH' },
  { symbol: 'LH.BK', name: 'Land and Houses Public Company Limited', sector: 'Property Development', market: 'TH' },
  { symbol: 'TIDLOR.BK', name: 'Ngern Tid Lor Public Company Limited', sector: 'Finance & Securities', market: 'TH' },
  { symbol: 'MTC.BK', name: 'Muangthai Capital Public Company Limited', sector: 'Finance & Securities', market: 'TH' },
  { symbol: 'SAWAD.BK', name: 'Srisawad Corporation Public Company Limited', sector: 'Finance & Securities', market: 'TH' },
  { symbol: 'BGRIM.BK', name: 'B.Grimm Power Public Company Limited', sector: 'Energy & Utilities', market: 'TH' },
  { symbol: 'CRC.BK', name: 'Central Retail Corporation Public Company Limited', sector: 'Commerce', market: 'TH' },
  { symbol: 'CPF.BK', name: 'Charoen Pokphand Foods Public Company Limited', sector: 'Agribusiness', market: 'TH' },
  { symbol: 'TU.BK', name: 'Thai Union Group Public Company Limited', sector: 'Food & Beverage', market: 'TH' },
  { symbol: 'WHA.BK', name: 'WHA Corporation Public Company Limited', sector: 'Property Development', market: 'TH' },
  { symbol: 'AMATA.BK', name: 'Amata Corporation Public Company Limited', sector: 'Property Development', market: 'TH' },
  { symbol: 'BH.BK', name: 'Bumrungrad Hospital Public Company Limited', sector: 'Health Care Services', market: 'TH' },
  { symbol: 'HANA.BK', name: 'Hana Microelectronics Public Company Limited', sector: 'Electronic Components', market: 'TH' },
  { symbol: 'KCE.BK', name: 'KCE Electronics Public Company Limited', sector: 'Electronic Components', market: 'TH' },
  { symbol: 'STA.BK', name: 'Sri Trang Agro-Industry Public Company Limited', sector: 'Agribusiness', market: 'TH' },
  { symbol: 'STGT.BK', name: 'Sri Trang Gloves (Thailand) Public Company Limited', sector: 'Personal Products & Pharmaceuticals', market: 'TH' },
  { symbol: 'COM7.BK', name: 'Com7 Public Company Limited', sector: 'Commerce', market: 'TH' },
  { symbol: 'JMART.BK', name: 'Jay Mart Public Company Limited', sector: 'Commerce', market: 'TH' },
  { symbol: 'JMT.BK', name: 'JMT Network Services Public Company Limited', sector: 'Finance & Securities', market: 'TH' },
  { symbol: 'TISCO.BK', name: 'TISCO Financial Group Public Company Limited', sector: 'Banking', market: 'TH' },
  { symbol: 'KKP.BK', name: 'Kiatnakin Phatra Bank Public Company Limited', sector: 'Banking', market: 'TH' },
];

// US STOCKS (S&P 500 focus)
export const US_STOCKS: StockMetadata[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Technology', market: 'US' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'TSLA', name: 'Tesla, Inc.', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Technology', market: 'US' },
  { symbol: 'META', name: 'Meta Platforms, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Inc.', sector: 'Financials', market: 'US' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financials', market: 'US' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health Care', market: 'US' },
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financials', market: 'US' },
  { symbol: 'MA', name: 'Mastercard Incorporated', sector: 'Financials', market: 'US' },
  { symbol: 'PG', name: 'Procter & Gamble Company', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated', sector: 'Health Care', market: 'US' },
  { symbol: 'HD', name: 'The Home Depot, Inc.', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'BAC', name: 'Bank of America Corporation', sector: 'Financials', market: 'US' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Health Care', market: 'US' },
  { symbol: 'DIS', name: 'The Walt Disney Company', sector: 'Communication Services', market: 'US' },
  { symbol: 'NFLX', name: 'Netflix, Inc.', sector: 'Communication Services', market: 'US' },
  { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'CRM', name: 'Salesforce, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'CSCO', name: 'Cisco Systems, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Technology', market: 'US' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'PYPL', name: 'PayPal Holdings, Inc.', sector: 'Financials', market: 'US' },
  { symbol: 'NKE', name: 'NIKE, Inc.', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', sector: 'Energy', market: 'US' },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy', market: 'US' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', sector: 'Health Care', market: 'US' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Health Care', market: 'US' },
  { symbol: 'MRK', name: 'Merck & Co., Inc.', sector: 'Health Care', market: 'US' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology', market: 'US' },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Technology', market: 'US' },
  { symbol: 'ACN', name: 'Accenture plc', sector: 'Technology', market: 'US' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.', sector: 'Health Care', market: 'US' },
  { symbol: 'MCD', name: 'McDonald\'s Corporation', sector: 'Consumer Discretionary', market: 'US' },
  { symbol: 'NXT', name: 'NextEra Energy, Inc.', sector: 'Utilities', market: 'US' },
  { symbol: 'LIN', name: 'Linde plc', sector: 'Materials', market: 'US' },
  { symbol: 'PM', name: 'Philip Morris International Inc.', sector: 'Consumer Staples', market: 'US' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated', sector: 'Technology', market: 'US' },
  { symbol: 'UPS', name: 'United Parcel Service, Inc.', sector: 'Industrials', market: 'US' },
  { symbol: 'HON', name: 'Honeywell International Inc.', sector: 'Industrials', market: 'US' },
  { symbol: 'RTX', name: 'Raytheon Technologies Corporation', sector: 'Industrials', market: 'US' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation', sector: 'Industrials', market: 'US' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials', market: 'US' },
  { symbol: 'GE', name: 'General Electric Company', sector: 'Industrials', market: 'US' },
];

export const STOCK_LIST: StockMetadata[] = [...TH_STOCKS, ...US_STOCKS];
